language: cpp
compiler: gcc
dist: bionic
sudo: required

addons:
    sonarcloud:
        organization: "gbaudic-github"

before_install:
    - sudo apt-get update -qq
    - wget https://www.libsdl.org/release/SDL2-2.0.10.tar.gz && tar -xzf SDL2-2.0.10.tar.gz
    - pushd SDL2-2.0.10 && ./configure && make && sudo make install && popd
    - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz && tar -xzf SDL2_image-2.0.5.tar.gz
    - pushd SDL2_image-2.0.5 && ./configure && make && sudo make install && popd
    - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz && tar -xzf SDL2_ttf-2.0.15.tar.gz
    - pushd SDL2_ttf-2.0.15 && ./configure && make && sudo make install && popd 
    - wget https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.1.tar.gz && tar -xzf SDL2_net-2.0.1.tar.gz
    - pushd SDL2_net-2.0.1 && ./configure && make && sudo make install && popd
    - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz && tar -xzf SDL2_mixer-2.0.4.tar.gz
    - pushd SDL2_mixer-2.0.4 && ./configure && make && sudo make install && popd
    - wget https://github.com/leethomason/tinyxml2/archive/7.0.1.tar.gz && tar -xzf 7.0.1.tar.gz
    - pushd tinyxml2-7.0.1 && cmake . -DBUILD_STATIC_LIBS:BOOL=ON && make && sudo make install && popd
    - sudo apt-get install -qq libsqlite3-dev libbox2d-dev google-mock scons

install:
    - wget http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.4.tar.gz
    - tar -xzf SDL2_gfx-1.0.4.tar.gz
    - pushd SDL2_gfx-1.0.4 && ./configure && make && sudo make install && popd
    - git clone https://github.com/gbaudic/guisan.git
    - pushd guisan && scons && sudo scons install && popd
    - git clone https://github.com/google/googletest.git
    - pushd googletest && cmake -DCMAKE_CXX_STANDARD=11 . && sudo make install && popd

script:
    - cmake -DENABLE_SERVER=ON .
    - build-wrapper-linux-x86-64 --out-dir bw-outputs make -j2
    - sonar-scanner
    - make -j2
    - ctest

cache:
    directories:
        - sonar-cache
