language: cpp
compiler: gcc
dist: bionic
sudo: required

addons:
    sonarcloud:
        organization: "gbaudic-github"

before_install:
    - sudo apt-get update -qq
    - wget https://github.com/leethomason/tinyxml2/archive/8.0.0.tar.gz && tar -xzf 8.0.0.tar.gz
    - pushd tinyxml2-8.0.0 && cmake . -DBUILD_STATIC_LIBS:BOOL=ON && make && sudo make install && popd
    - sudo apt-get install -qq libsdl2-dev libsdl2-net-dev libsdl2-ttf-dev libsdl2-gfx-dev libsdl2-mixer-dev libsdl2-image-dev libsqlite3-dev libbox2d-dev google-mock scons

install:
    - git clone https://github.com/gbaudic/guisan.git
    - pushd guisan && scons && sudo scons install && popd
    - git clone https://github.com/google/googletest.git
    - pushd googletest && cmake -DCMAKE_CXX_STANDARD=11 . && sudo make install && popd

script:
    - cmake -DENABLE_SERVER=ON -DRESOURCE_PREFIX=./res .
    - build-wrapper-linux-x86-64 --out-dir bw-outputs make -j2
    - sonar-scanner
    - make -j2
    - ctest

cache:
    directories:
        - sonar-cache
