language: cpp
compiler: gcc
dist: bionic
sudo: required

# Make sure we can init the video subsystem
services:
    - xvfb

addons:
    sonarcloud:
        organization: "gbaudic-github"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libsdl2-dev libsdl2-net-dev libsdl2-ttf-dev libsdl2-gfx-dev libsdl2-mixer-dev libsdl2-image-dev libsqlite3-dev libbox2d-dev google-mock scons libtinyxml2-dev

# Our fork of guisan, and the most up-to-date version of google test
install:
    - git clone https://github.com/gbaudic/guisan.git
    - pushd guisan && scons && sudo scons install && popd
    - git clone https://github.com/google/googletest.git
    - pushd googletest && cmake -DCMAKE_CXX_STANDARD=11 . && sudo make install && popd

script:
    - cmake -DENABLE_SERVER=ON -DRESOURCE_PREFIX=./res .
    - mkdir -p bin
    - pushd bin && ln -s ../res && popd
    - build-wrapper-linux-x86-64 --out-dir bw-outputs make -j2
    - sonar-scanner
    - make -j2
    - ctest

cache:
    directories:
        - sonar-cache
