image: Visual Studio 2017

install:
  - set PATH=C:\msys64\MINGW64\bin;C:\msys64\usr\bin;%PATH%
  - bash -lc "pacman -S --needed --noconfirm make cmake"
  - bash -lc "pacman --noconfirm -Suy mingw-w64-x86_64-sdl2 mingw-w64-x86_64-sdl2_gfx mingw-w64-x86_64-sdl2_image mingw-w64-x86_64-sdl2_mixer mingw-w64-x86_64-sdl2_net mingw-w64-x86_64-sdl2_ttf mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-tinyxml2 mingw-w64-x86_64-box2d mingw-w64-x86_64-gtest"
  - git clone https://github.com/gbaudic/guisan.git
  - cd guisan
  - bash -lc "scons && sudo scons install"
  - cd ..  
  
build_script:
  - bash -lc "cmake . && make" 

platform:
  - x64
  - Any CPU

configuration:
  - Debug
  - Release
  
matrix:
  fast_finish: true
