image: Visual Studio 2017
platform: x64

install:
  - set MSYSTEM=MINGW64
  - set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
  - bash -lc "pacman -S --needed --noconfirm make cmake scons"
  - bash -lc "pacman -Syu --noconfirm"
  - bash -lc "pacman --noconfirm -Sy mingw-w64-x86_64-toolchain mingw-w64-x86_64-readline mingw-w64-x86_64-python3 mingw-w64-x86_64-libc++ mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_gfx mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_net mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-tinyxml2 mingw-w64-x86_64-box2d mingw-w64-x86_64-gtest"
  - bash -lc "pacman -R --noconfirm mingw-w64-x86_64-pkg-config"
  - bash -lc "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/mingw64/lib/pkgconfig; git clone https://github.com/gbaudic/guisan.git && pushd guisan && scons prefix=/mingw64 && scons install prefix=/mingw64 && popd"  
  
build_script:
  - bash -lc "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/mingw64/lib/pkgconfig; cd $APPVEYOR_BUILD_FOLDER; mkdir build; cd build; CC=gcc CXX=g++ cmake .. && cmake --build . && ctest" 
  
matrix:
  fast_finish: true

# after_build:
  # - copy /b build\bin\linbound.exe linbound.exe
  # # Copy msys 64-bit DLLs into a dll subdir
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libBox2D.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libfreetype*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libgcc_s_seh*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libjpeg*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\liblzma*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libmpg123*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libogg*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libpng16*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libstdc++*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libtiff*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\SDL2*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libSDL2*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libvorbis*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libwebp*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libwinpthread*.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\libzstd.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\smpeg2.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\sqlite3.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\tinyxml2.dll dll\
  # - copy /b /y C:\msys64\%MSYSTEM%\bin\zlib1.dll dll\
  # - "C:\Program Files (x86)\Inno Setup 5\compil32" /cc linbound.iss
  
# artifacts:
  # - path: Output\LinboundSetup.exe
    # name: Setup
  
# deploy:
  # release: linbound-v$(appveyor_build_version)
  # description: 'Linbound v$(APPVEYOR_BUILD_VERSION)'
  # provider: GitHub
  # auth_token:
    # secure: oAzX3AMKStWmtHsjWEtqKv5kEXk/iDY102HMW15kXfVsxGfbBMGEiZLj/JwFxA4H
  # artifact: Output\LinboundSetup.exe     
  # draft: true
  # force_update: true
  # prerelease: false
  # on:
    # branch: master
    # APPVEYOR_REPO_TAG: true
