image: Visual Studio 2017

install:
  - set PATH=C:\msys64\MINGW64\bin;C:\msys64\usr\bin;%PATH%
  - bash -lc "pacman -S --needed --noconfirm make cmake"
  - bash -lc "pacman --noconfirm -Suy mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_gfx mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_net mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-tinyxml2 mingw-w64-x86_64-box2d mingw-w64-x86_64-gtest"
  - git clone https://github.com/gbaudic/guisan.git
  - bash -lc "pushd guisan && scons && sudo scons install && popd"  
  
build_script:
  - bash -lc "cmake . && make" 

#platform:
#  - x64
#  - Any CPU

#configuration:
#  - Debug
#  - Release
  
matrix:
  fast_finish: true
